package handlers

import (
	"time"

	"russ-rentals/internal/models"
)

// GetSampleProperties returns the sample property data
// This will be replaced with database queries once the DB is set up
func GetSampleProperties() []models.Property {
	availableDate1 := time.Date(2025, 2, 1, 0, 0, 0, 0, time.UTC)
	availableDate2 := time.Date(2025, 1, 15, 0, 0, 0, 0, time.UTC)
	availableDate3 := time.Date(2025, 2, 15, 0, 0, 0, 0, time.UTC)
	availableDate4 := time.Date(2025, 3, 1, 0, 0, 0, 0, time.UTC)
	availableDate5 := time.Date(2025, 1, 20, 0, 0, 0, 0, time.UTC)

	petDeposit1 := 300
	petRent1 := 35
	petDeposit2 := 250
	petRent2 := 30
	petDeposit3 := 400
	petRent3 := 50
	petDeposit4 := 200
	petRent4 := 25
	petDeposit5 := 350
	petRent5 := 40
	petDeposit6 := 500
	petRent6 := 75
	petDeposit7 := 250
	petRent7 := 30
	petDeposit8 := 200
	petRent8 := 25

	yearBuilt1 := 2015
	yearBuilt2 := 2020
	yearBuilt3 := 1998
	yearBuilt4 := 2018
	yearBuilt5 := 2019
	yearBuilt6 := 2005
	yearBuilt7 := 1905
	yearBuilt8 := 2022
	yearBuilt9 := 2002
	yearBuilt10 := 1955

	return []models.Property{
		{
			ID:             1,
			Slug:           "spacious-family-home",
			Title:          "Spacious Family Home",
			Type:           models.PropertyTypeHouse,
			Address:        "123 Oak Street",
			City:           "Springfield",
			State:          "IL",
			ZipCode:        "62701",
			Price:          1850,
			Deposit:        1850,
			ApplicationFee: 50,
			Bedrooms:       4,
			Bathrooms:      2.5,
			SquareFeet:     2200,
			Description:    "Beautiful single-family home in a quiet neighborhood. This spacious property features an open floor plan, updated kitchen with stainless steel appliances, hardwood floors throughout the main level, and a large backyard perfect for families. The master suite includes a walk-in closet and ensuite bathroom. Located near excellent schools and parks.",
			Features: []string{
				"Central Air Conditioning",
				"Hardwood Floors",
				"Updated Kitchen",
				"Large Backyard",
				"Two-Car Garage",
				"Basement Storage",
				"Near Schools",
				"Quiet Neighborhood",
				"Fireplace",
				"Walk-in Closets",
			},
			Images: []models.PropertyImage{
				{ID: 1, PropertyID: 1, URL: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200", Caption: "Front exterior view", Room: models.RoomTypeExterior, DisplayOrder: 0},
				{ID: 2, PropertyID: 1, URL: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200", Caption: "Curb appeal with landscaping", Room: models.RoomTypeExterior, DisplayOrder: 1},
				{ID: 3, PropertyID: 1, URL: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200", Caption: "Spacious living room with fireplace", Room: models.RoomTypeLiving, DisplayOrder: 2},
				{ID: 4, PropertyID: 1, URL: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200", Caption: "Open concept living area", Room: models.RoomTypeLiving, DisplayOrder: 3},
				{ID: 5, PropertyID: 1, URL: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200", Caption: "Modern kitchen with stainless appliances", Room: models.RoomTypeKitchen, DisplayOrder: 4},
				{ID: 6, PropertyID: 1, URL: "https://images.unsplash.com/photo-1556909172-8c2f041fca1e?w=1200", Caption: "Kitchen island and breakfast bar", Room: models.RoomTypeKitchen, DisplayOrder: 5},
				{ID: 7, PropertyID: 1, URL: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200", Caption: "Master bedroom with natural light", Room: models.RoomTypeBedroom, DisplayOrder: 6},
				{ID: 8, PropertyID: 1, URL: "https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=1200", Caption: "Second bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 7},
				{ID: 9, PropertyID: 1, URL: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200", Caption: "Kids bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 8},
				{ID: 10, PropertyID: 1, URL: "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=1200", Caption: "Guest bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 9},
				{ID: 11, PropertyID: 1, URL: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200", Caption: "Master bathroom with double vanity", Room: models.RoomTypeBathroom, DisplayOrder: 10},
				{ID: 12, PropertyID: 1, URL: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200", Caption: "Hall bathroom", Room: models.RoomTypeBathroom, DisplayOrder: 11},
				{ID: 13, PropertyID: 1, URL: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=1200", Caption: "Dining room", Room: models.RoomTypeDining, DisplayOrder: 12},
				{ID: 14, PropertyID: 1, URL: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200", Caption: "Backyard with patio", Room: models.RoomTypeBackyard, DisplayOrder: 13},
				{ID: 15, PropertyID: 1, URL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200", Caption: "Two-car garage", Room: models.RoomTypeGarage, DisplayOrder: 14},
			},
			Available:     true,
			AvailableDate: &availableDate1,
			PetFriendly:   true,
			PetDeposit:    &petDeposit1,
			PetRent:       &petRent1,
			Parking:       "2-Car Attached Garage",
			Laundry:       "In-Unit (Washer/Dryer Included)",
			YearBuilt:     &yearBuilt1,
			Utilities:     []string{"Tenant pays electric", "Tenant pays gas", "Water included", "Trash included"},
			LeaseTerms:    []string{"12-month lease", "24-month lease available"},
			Featured:      true,
		},
		{
			ID:             2,
			Slug:           "modern-downtown-apartment",
			Title:          "Modern Downtown Apartment",
			Type:           models.PropertyTypeApartment,
			Address:        "456 Main Avenue, Unit 5B",
			City:           "Springfield",
			State:          "IL",
			ZipCode:        "62702",
			Price:          1200,
			Deposit:        1200,
			ApplicationFee: 45,
			Bedrooms:       2,
			Bathrooms:      1,
			SquareFeet:     950,
			Description:    "Contemporary apartment in the heart of downtown. Enjoy city living with modern amenities including granite countertops, stainless steel appliances, and in-unit laundry. Building features include a fitness center, rooftop terrace, and secure entry. Walking distance to restaurants, shops, and public transportation.",
			Features: []string{
				"Granite Countertops",
				"Stainless Steel Appliances",
				"In-Unit Laundry",
				"Fitness Center",
				"Rooftop Terrace",
				"Secure Entry",
				"Walking Distance to Transit",
				"Pet-Friendly Building",
				"Central Heat & AC",
				"High-Speed Internet Ready",
			},
			Images: []models.PropertyImage{
				{ID: 16, PropertyID: 2, URL: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200", Caption: "Open concept living space", Room: models.RoomTypeLiving, DisplayOrder: 0},
				{ID: 17, PropertyID: 2, URL: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200", Caption: "Modern living room", Room: models.RoomTypeLiving, DisplayOrder: 1},
				{ID: 18, PropertyID: 2, URL: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200", Caption: "Living room with city views", Room: models.RoomTypeLiving, DisplayOrder: 2},
				{ID: 19, PropertyID: 2, URL: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200", Caption: "Updated kitchen with granite", Room: models.RoomTypeKitchen, DisplayOrder: 3},
				{ID: 20, PropertyID: 2, URL: "https://images.unsplash.com/photo-1556909172-8c2f041fca1e?w=1200", Caption: "Kitchen with breakfast bar", Room: models.RoomTypeKitchen, DisplayOrder: 4},
				{ID: 21, PropertyID: 2, URL: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200", Caption: "Primary bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 5},
				{ID: 22, PropertyID: 2, URL: "https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=1200", Caption: "Second bedroom/office", Room: models.RoomTypeBedroom, DisplayOrder: 6},
				{ID: 23, PropertyID: 2, URL: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200", Caption: "Full bathroom", Room: models.RoomTypeBathroom, DisplayOrder: 7},
				{ID: 24, PropertyID: 2, URL: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=1200", Caption: "Building exterior", Room: models.RoomTypeExterior, DisplayOrder: 8},
				{ID: 25, PropertyID: 2, URL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200", Caption: "Rooftop terrace", Room: models.RoomTypeOther, DisplayOrder: 9},
			},
			Available:   true,
			PetFriendly: true,
			PetDeposit:  &petDeposit2,
			PetRent:     &petRent2,
			Parking:     "Underground Parking ($75/mo)",
			Laundry:     "In-Unit (Washer/Dryer Included)",
			YearBuilt:   &yearBuilt2,
			Utilities:   []string{"Water included", "Trash included", "Tenant pays electric"},
			LeaseTerms:  []string{"12-month lease", "6-month lease (+$100/mo)"},
			Featured:    true,
		},
		{
			ID:             3,
			Slug:           "charming-duplex-unit",
			Title:          "Charming Duplex Unit",
			Type:           models.PropertyTypeDuplex,
			Address:        "789 Elm Street, Unit A",
			City:           "Springfield",
			State:          "IL",
			ZipCode:        "62703",
			Price:          1450,
			Deposit:        1450,
			ApplicationFee: 45,
			Bedrooms:       3,
			Bathrooms:      2,
			SquareFeet:     1400,
			Description:    "Well-maintained duplex unit offering the perfect blend of privacy and convenience. Features include a private entrance, updated bathrooms, eat-in kitchen, and private backyard space. This unit has been recently renovated with new flooring, fresh paint, and modern fixtures throughout.",
			Features: []string{
				"Private Entrance",
				"Updated Bathrooms",
				"Eat-In Kitchen",
				"Private Backyard",
				"Recently Renovated",
				"New Flooring",
				"Dedicated Parking",
				"Storage Space",
				"Central Air",
				"Ceiling Fans",
			},
			Images: []models.PropertyImage{
				{ID: 26, PropertyID: 3, URL: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200", Caption: "Front of duplex unit", Room: models.RoomTypeExterior, DisplayOrder: 0},
				{ID: 27, PropertyID: 3, URL: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200", Caption: "Private entrance", Room: models.RoomTypeExterior, DisplayOrder: 1},
				{ID: 28, PropertyID: 3, URL: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200", Caption: "Bright living room", Room: models.RoomTypeLiving, DisplayOrder: 2},
				{ID: 29, PropertyID: 3, URL: "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1200", Caption: "Living area with new flooring", Room: models.RoomTypeLiving, DisplayOrder: 3},
				{ID: 30, PropertyID: 3, URL: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200", Caption: "Eat-in kitchen", Room: models.RoomTypeKitchen, DisplayOrder: 4},
				{ID: 31, PropertyID: 3, URL: "https://images.unsplash.com/photo-1556909172-8c2f041fca1e?w=1200", Caption: "Kitchen with modern appliances", Room: models.RoomTypeKitchen, DisplayOrder: 5},
				{ID: 32, PropertyID: 3, URL: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200", Caption: "Master bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 6},
				{ID: 33, PropertyID: 3, URL: "https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=1200", Caption: "Second bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 7},
				{ID: 34, PropertyID: 3, URL: "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=1200", Caption: "Third bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 8},
				{ID: 35, PropertyID: 3, URL: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200", Caption: "Updated master bathroom", Room: models.RoomTypeBathroom, DisplayOrder: 9},
				{ID: 36, PropertyID: 3, URL: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200", Caption: "Second full bathroom", Room: models.RoomTypeBathroom, DisplayOrder: 10},
				{ID: 37, PropertyID: 3, URL: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200", Caption: "Private backyard", Room: models.RoomTypeBackyard, DisplayOrder: 11},
			},
			Available:     true,
			AvailableDate: &availableDate2,
			PetFriendly:   false,
			Parking:       "Driveway - 2 Spaces",
			Laundry:       "In-Unit (Hookups Only)",
			YearBuilt:     &yearBuilt3,
			Utilities:     []string{"Tenant pays all utilities"},
			LeaseTerms:    []string{"12-month lease required"},
			Featured:      true,
		},
		{
			ID:             4,
			Slug:           "cozy-studio-apartment",
			Title:          "Cozy Studio Apartment",
			Type:           models.PropertyTypeApartment,
			Address:        "321 Park Boulevard, Unit 12",
			City:           "Springfield",
			State:          "IL",
			ZipCode:        "62702",
			Price:          750,
			Deposit:        750,
			ApplicationFee: 35,
			Bedrooms:       0,
			Bathrooms:      1,
			SquareFeet:     450,
			Description:    "Efficient studio apartment perfect for young professionals or students. Features an open layout with a separate kitchen area, large windows providing excellent natural light, and modern finishes. Building amenities include laundry facilities, bike storage, and package lockers.",
			Features: []string{
				"Large Windows",
				"Modern Finishes",
				"Separate Kitchen Area",
				"Building Laundry",
				"Bike Storage",
				"Package Lockers",
				"Near Public Transit",
				"Utilities Included",
				"High Ceilings",
				"Hardwood Floors",
			},
			Images: []models.PropertyImage{
				{ID: 38, PropertyID: 4, URL: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=1200", Caption: "Open studio layout", Room: models.RoomTypeLiving, DisplayOrder: 0},
				{ID: 39, PropertyID: 4, URL: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200", Caption: "Living and sleeping area", Room: models.RoomTypeLiving, DisplayOrder: 1},
				{ID: 40, PropertyID: 4, URL: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=1200", Caption: "Cozy living space", Room: models.RoomTypeLiving, DisplayOrder: 2},
				{ID: 41, PropertyID: 4, URL: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200", Caption: "Large windows with natural light", Room: models.RoomTypeLiving, DisplayOrder: 3},
				{ID: 42, PropertyID: 4, URL: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200", Caption: "Kitchenette area", Room: models.RoomTypeKitchen, DisplayOrder: 4},
				{ID: 43, PropertyID: 4, URL: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200", Caption: "Updated bathroom", Room: models.RoomTypeBathroom, DisplayOrder: 5},
				{ID: 44, PropertyID: 4, URL: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=1200", Caption: "Building exterior", Room: models.RoomTypeExterior, DisplayOrder: 6},
				{ID: 45, PropertyID: 4, URL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200", Caption: "Building entrance", Room: models.RoomTypeExterior, DisplayOrder: 7},
			},
			Available:   true,
			PetFriendly: false,
			Parking:     "Street Parking (Free)",
			Laundry:     "Shared (On-Site)",
			YearBuilt:   &yearBuilt4,
			Utilities:   []string{"All utilities included"},
			LeaseTerms:  []string{"12-month lease", "Month-to-month (+$150/mo)"},
			Featured:    false,
		},
		{
			ID:             5,
			Slug:           "executive-townhouse",
			Title:          "Executive Townhouse",
			Type:           models.PropertyTypeHouse,
			Address:        "555 Maple Drive",
			City:           "Springfield",
			State:          "IL",
			ZipCode:        "62704",
			Price:          2400,
			Deposit:        2400,
			ApplicationFee: 60,
			Bedrooms:       3,
			Bathrooms:      2.5,
			SquareFeet:     1800,
			Description:    "Elegant townhouse in prestigious community. Features include high ceilings, crown molding, chef's kitchen with premium appliances, and a private patio. HOA maintains exterior and common areas. Community amenities include a pool, clubhouse, and fitness center.",
			Features: []string{
				"High Ceilings",
				"Crown Molding",
				"Chef's Kitchen",
				"Premium Appliances",
				"Private Patio",
				"Community Pool",
				"Fitness Center",
				"HOA Maintained",
				"Two-Car Garage",
				"Smart Home Features",
			},
			Images: []models.PropertyImage{
				{ID: 46, PropertyID: 5, URL: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200", Caption: "Elegant townhouse exterior", Room: models.RoomTypeExterior, DisplayOrder: 0},
				{ID: 47, PropertyID: 5, URL: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=1200", Caption: "Front entrance", Room: models.RoomTypeExterior, DisplayOrder: 1},
				{ID: 48, PropertyID: 5, URL: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200", Caption: "Grand living room", Room: models.RoomTypeLiving, DisplayOrder: 2},
				{ID: 49, PropertyID: 5, URL: "https://images.unsplash.com/photo-1600047509782-20d39509f26d?w=1200", Caption: "Living room with high ceilings", Room: models.RoomTypeLiving, DisplayOrder: 3},
				{ID: 50, PropertyID: 5, URL: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200", Caption: "Chef's kitchen", Room: models.RoomTypeKitchen, DisplayOrder: 4},
				{ID: 51, PropertyID: 5, URL: "https://images.unsplash.com/photo-1556909172-8c2f041fca1e?w=1200", Caption: "Premium appliances", Room: models.RoomTypeKitchen, DisplayOrder: 5},
				{ID: 52, PropertyID: 5, URL: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=1200", Caption: "Formal dining room", Room: models.RoomTypeDining, DisplayOrder: 6},
				{ID: 53, PropertyID: 5, URL: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200", Caption: "Master suite", Room: models.RoomTypeBedroom, DisplayOrder: 7},
				{ID: 54, PropertyID: 5, URL: "https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=1200", Caption: "Second bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 8},
				{ID: 55, PropertyID: 5, URL: "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=1200", Caption: "Third bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 9},
				{ID: 56, PropertyID: 5, URL: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200", Caption: "Master bathroom", Room: models.RoomTypeBathroom, DisplayOrder: 10},
				{ID: 57, PropertyID: 5, URL: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200", Caption: "Guest bathroom", Room: models.RoomTypeBathroom, DisplayOrder: 11},
				{ID: 58, PropertyID: 5, URL: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200", Caption: "Private patio", Room: models.RoomTypeBackyard, DisplayOrder: 12},
				{ID: 59, PropertyID: 5, URL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200", Caption: "Two-car garage", Room: models.RoomTypeGarage, DisplayOrder: 13},
			},
			Available:   false,
			PetFriendly: true,
			PetDeposit:  &petDeposit3,
			PetRent:     &petRent3,
			Parking:     "Attached 2-Car Garage",
			Laundry:     "In-Unit (Washer/Dryer Included)",
			YearBuilt:   &yearBuilt5,
			Utilities:   []string{"HOA fee $150/mo included", "Tenant pays electric", "Tenant pays gas"},
			LeaseTerms:  []string{"12-month lease", "24-month lease available"},
			Featured:    false,
		},
		{
			ID:             6,
			Slug:           "garden-level-apartment",
			Title:          "Garden Level Apartment",
			Type:           models.PropertyTypeApartment,
			Address:        "888 River Road, Unit G1",
			City:           "Springfield",
			State:          "IL",
			ZipCode:        "62701",
			Price:          950,
			Deposit:        950,
			ApplicationFee: 40,
			Bedrooms:       1,
			Bathrooms:      1,
			SquareFeet:     700,
			Description:    "Quiet garden-level apartment with private patio access. Recently updated with new appliances, fresh paint, and luxury vinyl flooring. Perfect for those seeking a peaceful retreat with easy access to walking trails and parks.",
			Features: []string{
				"Private Patio",
				"New Appliances",
				"Luxury Vinyl Flooring",
				"Near Walking Trails",
				"Peaceful Setting",
				"Updated Interior",
				"On-Site Management",
				"Responsive Maintenance",
				"Central Air",
				"Storage Unit Included",
			},
			Images: []models.PropertyImage{
				{ID: 60, PropertyID: 6, URL: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200", Caption: "Bright living room", Room: models.RoomTypeLiving, DisplayOrder: 0},
				{ID: 61, PropertyID: 6, URL: "https://images.unsplash.com/photo-1600566752229-250ed79470f8?w=1200", Caption: "Living area with patio access", Room: models.RoomTypeLiving, DisplayOrder: 1},
				{ID: 62, PropertyID: 6, URL: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=1200", Caption: "Cozy living space", Room: models.RoomTypeLiving, DisplayOrder: 2},
				{ID: 63, PropertyID: 6, URL: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200", Caption: "Updated kitchen", Room: models.RoomTypeKitchen, DisplayOrder: 3},
				{ID: 64, PropertyID: 6, URL: "https://images.unsplash.com/photo-1556909172-8c2f041fca1e?w=1200", Caption: "New appliances", Room: models.RoomTypeKitchen, DisplayOrder: 4},
				{ID: 65, PropertyID: 6, URL: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200", Caption: "Comfortable bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 5},
				{ID: 66, PropertyID: 6, URL: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200", Caption: "Updated bathroom", Room: models.RoomTypeBathroom, DisplayOrder: 6},
				{ID: 67, PropertyID: 6, URL: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200", Caption: "Private patio", Room: models.RoomTypeBackyard, DisplayOrder: 7},
				{ID: 68, PropertyID: 6, URL: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=1200", Caption: "Building exterior", Room: models.RoomTypeExterior, DisplayOrder: 8},
				{ID: 69, PropertyID: 6, URL: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=1200", Caption: "Garden area", Room: models.RoomTypeOther, DisplayOrder: 9},
			},
			Available:     true,
			AvailableDate: &availableDate3,
			PetFriendly:   true,
			PetDeposit:    &petDeposit4,
			PetRent:       &petRent4,
			Parking:       "Assigned Parking Space",
			Laundry:       "Shared (On-Site)",
			YearBuilt:     &yearBuilt6,
			Utilities:     []string{"Water included", "Trash included", "Tenant pays electric"},
			LeaseTerms:    []string{"12-month lease"},
			Featured:      false,
		},
		{
			ID:             7,
			Slug:           "renovated-victorian-house",
			Title:          "Renovated Victorian House",
			Type:           models.PropertyTypeHouse,
			Address:        "234 Heritage Lane",
			City:           "Springfield",
			State:          "IL",
			ZipCode:        "62701",
			Price:          2100,
			Deposit:        2100,
			ApplicationFee: 55,
			Bedrooms:       4,
			Bathrooms:      3,
			SquareFeet:     2500,
			Description:    "Beautifully renovated Victorian home blending historic charm with modern amenities. Original hardwood floors, decorative moldings, and high ceilings preserved. Updated kitchen and bathrooms, new HVAC system, and energy-efficient windows. Large wrap-around porch and mature landscaping.",
			Features: []string{
				"Original Hardwood Floors",
				"High Ceilings (10ft)",
				"Wrap-Around Porch",
				"Updated Kitchen",
				"Modern Bathrooms",
				"New HVAC System",
				"Energy-Efficient Windows",
				"Mature Landscaping",
				"Detached Garage",
				"Full Basement",
			},
			Images: []models.PropertyImage{
				{ID: 70, PropertyID: 7, URL: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1200", Caption: "Victorian exterior with porch", Room: models.RoomTypeExterior, DisplayOrder: 0},
				{ID: 71, PropertyID: 7, URL: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200", Caption: "Front view with landscaping", Room: models.RoomTypeExterior, DisplayOrder: 1},
				{ID: 72, PropertyID: 7, URL: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200", Caption: "Living room with original details", Room: models.RoomTypeLiving, DisplayOrder: 2},
				{ID: 73, PropertyID: 7, URL: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200", Caption: "Parlor room", Room: models.RoomTypeLiving, DisplayOrder: 3},
				{ID: 74, PropertyID: 7, URL: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200", Caption: "Modern updated kitchen", Room: models.RoomTypeKitchen, DisplayOrder: 4},
				{ID: 75, PropertyID: 7, URL: "https://images.unsplash.com/photo-1556909172-8c2f041fca1e?w=1200", Caption: "Kitchen with island", Room: models.RoomTypeKitchen, DisplayOrder: 5},
				{ID: 76, PropertyID: 7, URL: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=1200", Caption: "Formal dining room", Room: models.RoomTypeDining, DisplayOrder: 6},
				{ID: 77, PropertyID: 7, URL: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200", Caption: "Master bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 7},
				{ID: 78, PropertyID: 7, URL: "https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=1200", Caption: "Second bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 8},
				{ID: 79, PropertyID: 7, URL: "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=1200", Caption: "Third bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 9},
				{ID: 80, PropertyID: 7, URL: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200", Caption: "Fourth bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 10},
				{ID: 81, PropertyID: 7, URL: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200", Caption: "Updated master bath", Room: models.RoomTypeBathroom, DisplayOrder: 11},
				{ID: 82, PropertyID: 7, URL: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200", Caption: "Hall bathroom", Room: models.RoomTypeBathroom, DisplayOrder: 12},
				{ID: 83, PropertyID: 7, URL: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200", Caption: "Backyard", Room: models.RoomTypeBackyard, DisplayOrder: 13},
				{ID: 84, PropertyID: 7, URL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200", Caption: "Detached garage", Room: models.RoomTypeGarage, DisplayOrder: 14},
			},
			Available:     true,
			AvailableDate: &availableDate4,
			PetFriendly:   true,
			PetDeposit:    &petDeposit5,
			PetRent:       &petRent5,
			Parking:       "Detached 2-Car Garage",
			Laundry:       "In-Unit (Washer/Dryer Included)",
			YearBuilt:     &yearBuilt7,
			Utilities:     []string{"Tenant pays all utilities"},
			LeaseTerms:    []string{"12-month lease", "18-month lease available"},
			Featured:      false,
		},
		{
			ID:             8,
			Slug:           "luxury-penthouse-suite",
			Title:          "Luxury Penthouse Suite",
			Type:           models.PropertyTypeApartment,
			Address:        "100 Skyline Tower, PH1",
			City:           "Springfield",
			State:          "IL",
			ZipCode:        "62702",
			Price:          3200,
			Deposit:        3200,
			ApplicationFee: 75,
			Bedrooms:       2,
			Bathrooms:      2,
			SquareFeet:     1600,
			Description:    "Stunning penthouse apartment with panoramic city views. Floor-to-ceiling windows, private terrace, premium finishes throughout. Features include chef's kitchen with high-end appliances, spa-like bathrooms, and smart home technology. Building amenities include concierge, valet parking, and rooftop pool.",
			Features: []string{
				"Panoramic City Views",
				"Private Terrace",
				"Floor-to-Ceiling Windows",
				"Chef's Kitchen",
				"Spa Bathrooms",
				"Smart Home Technology",
				"Concierge Service",
				"Valet Parking",
				"Rooftop Pool",
				"Wine Storage",
			},
			Images: []models.PropertyImage{
				{ID: 85, PropertyID: 8, URL: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200", Caption: "Stunning living space", Room: models.RoomTypeLiving, DisplayOrder: 0},
				{ID: 86, PropertyID: 8, URL: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200", Caption: "Floor-to-ceiling windows", Room: models.RoomTypeLiving, DisplayOrder: 1},
				{ID: 87, PropertyID: 8, URL: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200", Caption: "Open concept design", Room: models.RoomTypeLiving, DisplayOrder: 2},
				{ID: 88, PropertyID: 8, URL: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200", Caption: "Gourmet kitchen", Room: models.RoomTypeKitchen, DisplayOrder: 3},
				{ID: 89, PropertyID: 8, URL: "https://images.unsplash.com/photo-1556909172-8c2f041fca1e?w=1200", Caption: "Premium appliances", Room: models.RoomTypeKitchen, DisplayOrder: 4},
				{ID: 90, PropertyID: 8, URL: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200", Caption: "Master suite with views", Room: models.RoomTypeBedroom, DisplayOrder: 5},
				{ID: 91, PropertyID: 8, URL: "https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=1200", Caption: "Guest bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 6},
				{ID: 92, PropertyID: 8, URL: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200", Caption: "Spa-like master bath", Room: models.RoomTypeBathroom, DisplayOrder: 7},
				{ID: 93, PropertyID: 8, URL: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200", Caption: "Guest bathroom", Room: models.RoomTypeBathroom, DisplayOrder: 8},
				{ID: 94, PropertyID: 8, URL: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=1200", Caption: "Private terrace", Room: models.RoomTypeBackyard, DisplayOrder: 9},
				{ID: 95, PropertyID: 8, URL: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=1200", Caption: "Building exterior", Room: models.RoomTypeExterior, DisplayOrder: 10},
				{ID: 96, PropertyID: 8, URL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200", Caption: "Rooftop pool", Room: models.RoomTypeOther, DisplayOrder: 11},
			},
			Available:   true,
			PetFriendly: true,
			PetDeposit:  &petDeposit6,
			PetRent:     &petRent6,
			Parking:     "Valet Parking (2 Spaces Included)",
			Laundry:     "In-Unit (Premium Washer/Dryer)",
			YearBuilt:   &yearBuilt8,
			Utilities:   []string{"Water included", "Trash included", "Tenant pays electric"},
			LeaseTerms:  []string{"12-month lease", "24-month lease available"},
			Featured:    false,
		},
		{
			ID:             9,
			Slug:           "side-by-side-duplex",
			Title:          "Side-by-Side Duplex",
			Type:           models.PropertyTypeDuplex,
			Address:        "456 Cedar Court, Unit B",
			City:           "Springfield",
			State:          "IL",
			ZipCode:        "62703",
			Price:          1350,
			Deposit:        1350,
			ApplicationFee: 45,
			Bedrooms:       2,
			Bathrooms:      1.5,
			SquareFeet:     1100,
			Description:    "Well-maintained side-by-side duplex in family-friendly neighborhood. Features include a private entrance, fenced backyard, and dedicated parking. Updated kitchen with new cabinets and appliances. Half bath on main level, full bath upstairs. Close to schools and shopping.",
			Features: []string{
				"Private Entrance",
				"Fenced Backyard",
				"Dedicated Parking",
				"New Kitchen Cabinets",
				"Updated Appliances",
				"Family-Friendly Area",
				"Near Schools",
				"Central Air",
				"Ceiling Fans",
				"Storage Shed",
			},
			Images: []models.PropertyImage{
				{ID: 97, PropertyID: 9, URL: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200", Caption: "Duplex exterior", Room: models.RoomTypeExterior, DisplayOrder: 0},
				{ID: 98, PropertyID: 9, URL: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200", Caption: "Private entrance", Room: models.RoomTypeExterior, DisplayOrder: 1},
				{ID: 99, PropertyID: 9, URL: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200", Caption: "Living room", Room: models.RoomTypeLiving, DisplayOrder: 2},
				{ID: 100, PropertyID: 9, URL: "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1200", Caption: "Open living space", Room: models.RoomTypeLiving, DisplayOrder: 3},
				{ID: 101, PropertyID: 9, URL: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200", Caption: "Updated kitchen", Room: models.RoomTypeKitchen, DisplayOrder: 4},
				{ID: 102, PropertyID: 9, URL: "https://images.unsplash.com/photo-1556909172-8c2f041fca1e?w=1200", Caption: "New cabinets and appliances", Room: models.RoomTypeKitchen, DisplayOrder: 5},
				{ID: 103, PropertyID: 9, URL: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200", Caption: "Master bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 6},
				{ID: 104, PropertyID: 9, URL: "https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=1200", Caption: "Second bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 7},
				{ID: 105, PropertyID: 9, URL: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200", Caption: "Full bathroom", Room: models.RoomTypeBathroom, DisplayOrder: 8},
				{ID: 106, PropertyID: 9, URL: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200", Caption: "Fenced backyard", Room: models.RoomTypeBackyard, DisplayOrder: 9},
			},
			Available:     true,
			AvailableDate: &availableDate5,
			PetFriendly:   true,
			PetDeposit:    &petDeposit7,
			PetRent:       &petRent7,
			Parking:       "Driveway - 2 Spaces",
			Laundry:       "In-Unit (Hookups Only)",
			YearBuilt:     &yearBuilt9,
			Utilities:     []string{"Tenant pays all utilities"},
			LeaseTerms:    []string{"12-month lease required"},
			Featured:      false,
		},
		{
			ID:             10,
			Slug:           "starter-home-bungalow",
			Title:          "Starter Home Bungalow",
			Type:           models.PropertyTypeHouse,
			Address:        "789 Willow Way",
			City:           "Springfield",
			State:          "IL",
			ZipCode:        "62705",
			Price:          1100,
			Deposit:        1100,
			ApplicationFee: 40,
			Bedrooms:       2,
			Bathrooms:      1,
			SquareFeet:     900,
			Description:    "Charming bungalow perfect for first-time renters or downsizers. Features a cozy living room, eat-in kitchen, and nice-sized backyard. Recent updates include new roof, updated electrical, and fresh paint throughout. Quiet street with friendly neighbors.",
			Features: []string{
				"New Roof",
				"Updated Electrical",
				"Fresh Paint",
				"Cozy Living Room",
				"Eat-In Kitchen",
				"Nice Backyard",
				"Quiet Street",
				"Detached Garage",
				"Central Heat",
				"Window AC Units Provided",
			},
			Images: []models.PropertyImage{
				{ID: 107, PropertyID: 10, URL: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200", Caption: "Charming bungalow exterior", Room: models.RoomTypeExterior, DisplayOrder: 0},
				{ID: 108, PropertyID: 10, URL: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200", Caption: "Front yard", Room: models.RoomTypeExterior, DisplayOrder: 1},
				{ID: 109, PropertyID: 10, URL: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200", Caption: "Cozy living room", Room: models.RoomTypeLiving, DisplayOrder: 2},
				{ID: 110, PropertyID: 10, URL: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200", Caption: "Living area", Room: models.RoomTypeLiving, DisplayOrder: 3},
				{ID: 111, PropertyID: 10, URL: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200", Caption: "Eat-in kitchen", Room: models.RoomTypeKitchen, DisplayOrder: 4},
				{ID: 112, PropertyID: 10, URL: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200", Caption: "Master bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 5},
				{ID: 113, PropertyID: 10, URL: "https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=1200", Caption: "Second bedroom", Room: models.RoomTypeBedroom, DisplayOrder: 6},
				{ID: 114, PropertyID: 10, URL: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200", Caption: "Bathroom", Room: models.RoomTypeBathroom, DisplayOrder: 7},
				{ID: 115, PropertyID: 10, URL: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200", Caption: "Backyard", Room: models.RoomTypeBackyard, DisplayOrder: 8},
				{ID: 116, PropertyID: 10, URL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200", Caption: "Detached garage", Room: models.RoomTypeGarage, DisplayOrder: 9},
			},
			Available:   true,
			PetFriendly: true,
			PetDeposit:  &petDeposit8,
			PetRent:     &petRent8,
			Parking:     "Detached 1-Car Garage",
			Laundry:     "In-Unit (Hookups Only)",
			YearBuilt:   &yearBuilt10,
			Utilities:   []string{"Tenant pays all utilities"},
			LeaseTerms:  []string{"12-month lease", "6-month lease (+$75/mo)"},
			Featured:    false,
		},
	}
}
